apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-auth-secret-sealed.yml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 22.0.7
    releaseName: redis
    namespace: index-redis-prod
    valuesFile: redis-values.yml
