apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAJdIs2zjrY/2x41ND8b0njHdx83sAiZY5OEGc+R0ZhTDdtKpe0z+9l+dXRYh2aNuCGx1WPcUzcjSyfHceXNivKSNIWIr+Svjqgs11qIiZ9Y/PG/koVlVzxkOAxoa3S7fHki7ihdze460sXEoebZ+fgb2WTZADfaXuGKKCnazGCS3u66hYHALH70F6IBuIbejb58ICrBcFgudNpxxjXObmY6J/yRGdotUGtds5RgByMZsN4hf7Sx2LMukQTgUCP3+b46d9eHtPmgGNVckYpL6AD0MEKxfuJZi5+g+qtElPSFh6WxMZEqLy2hC66bL044XH8F1AlOC+4MDkoMMlOm8oEvSidWUusCzekWJVUOWO1eOjI15GCU/eDKFKOUVgAQRt8duP2jrYGsAuANEEt8b9QKkIFi10MrhemCsVfXit2x6s1g4ddLWZyBvj/Q8qg36j3wMfogdXzcBztitvkGPkD8vuIh/510I8J/6ABnVZ3mZN+tSD9w+GqhscDIUTE9etTgus/qs2RucCiS+6voYdRVeYwSimX3gBxZ/UTmkpVWfl01aEem1Ncvx0b08/0o7P1gMAQ0uI9Nw9bq+VA3bE/JD8pbZ4GGoRmtUFSaUKwEgq2rPMU6YvlCaF2RdlYomFlflDRLTS55LP3vD+fyMJdeNE31XRO187yy+e7+++UdzGm4p45FQT1JbxJKN2sV7PWBMEJ+ro2/j1SKSo+XrnZPLN8Mx5egR9v+3U3t5T356iOS603tYa0h+XQNXyxH9/RUNDfPfmVpfP0+Qa+A+j2
  template:
    metadata:
      name: redis-auth
      namespace: index-redis-prod
    type: Opaque
