apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: index-redis-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgARRpAdkD8ICKOOhb8O4XAN7eSQUv73Abm5fGlOA8hKSkpH1vkdVybDSU+YizZa7otTRkMRxa64JUW/0Xrg+nyyb+DVXSyRXwgvffcb+ojVI+263YRh5BG2PMuhZF2DSTFg0KiMJqDYjyKmoCbO7bRPJEgjF/jZa2VfSkE/Xk2s1HKahMF2wgJyiziCEc2Z0COF3kYeKeA1nSpHV8aibZFvhF/a5JZOyJJ9/vpzWsHlILC9rNjo+6XF1AygywjpGjp9lZ4wWtcepC7RoXoK6zvu+SccWW02W5ZkWIZD+cfT4kL1E2zwGUsP200ctA/YbhE9XlUfHsH+o7UTDK0GyVNSQKw2J81IKPDFqgrhu+TSzRutBHg4sE/KmCq0xj1RD6h/6qzmASZrHoh4o++JiAcj25EwEB8mhsJPMiokJ0OSCZeb9Qq8vGcNTt3HHy+550ZLO4ZCV/DWOJ+fgghj0AXlH6UD063w3TzPRScJMEwYiRn75XRbXlm5n9mRPnshz7L0QpgzKL5CLTD8+dGuZbe+SPag3iRVHm//IhkX+ug2/J2ilgx2t8PbAq36xxuBLSctvQeMqUvEXvcLXRRgrqyD8Z5waWdUZw8UqyPNI8ZUXKHW5KTXpU9m++xuINe9TOhCHCZWPiUhzV1q4rX7H0XvGaXdofeBn83za1n3p3OZTcmIjZQfbC52+Qj2FukN6hk/RPVgQf1fhvosLJ7HiLwXLQK9TGXtSIckIcNU3TuMJajabp+CfovYiN9R76sEgkbkk+wRSobO3j5tHtkPTno/
  template:
    metadata:
      name: redis-auth
      namespace: index-redis-prod
    type: Opaque
