---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-config
  namespace: index-api-prod
spec:
  encryptedData:
    .dockerconfigjson: AgA73Aa+Q2Eqlv4c5gS4RHI8EDkNX54gCYf+Sb5tRcbxCJZakasOUR/F/hVYhPZzCnopIuAB7cY7rE5yVXRnD5nFRQ3vNZaCjatcRGTwD0cy23C8yN8zY91fFRlEb7gQBbUtd3KbBbngUd1pKEdvluKjgZEwnRZZ4FiZQkcxgo7VTPUZS1uLko++FGt8Up/oV18Wyf9fGNodPqyQNFtGV6DY4772L/0OwanQZqAx3eM0CxH61/S/G52eI8/uQqecV4aLnJ8H/B17LK38BskrQd89hXmKkBRtxar0MdeJp84aDLX+/z0HTGpcaPp2FoEnY39MKzuCKfYIHMpZLKlcdRc6yynBBEmOliTgjlVoV/MxeYHi0s3qIcPdUd3qIfTilgzwB40+jeVFEKdJ5fnCNaVL0s2NOFwUXWj8hB3sRPevpMbzMVnax1HtR6gQG8VF7sRfYZURhXaIYebMzTbU52qtJMnVW0NWvXXRepIRUtHYyVKN1NL1wX4b1teU5C5O6lIek8PpG5WkKDP6ZlXBl3i1+ARhGVwqGANJyJyNp7pnzKOYJgy6XFnepRfRwBkjteQROQItcOxI0Ap9tqvdULMi1PEurVChrXbMszV63QgrhugoCm6AiyJ7GZ1TBgWoP1gsnxLKXhXoOHFMG9ImAbVEhLuNnTwBmh9G6eH8TJA9m268rxbZPxBXQFGh63hOOFOaqpCO8JxDaPz87wQEYid2IeNauMgiBsRl+YgTQInME2zq5ojHKf0tpCoLHFUd9vwuUadZxf5QmV4j+8MzLmJt2UoITLhGZcDcgsgrwFWdWkVIQW3fVxitN5RXCzSZudJtWA0VX96qMSNxoXaRg6RT2wuBgj/xWbNP/dyEGjXmGD6zvytswWl9Z55HDrNCCSwxETrBhtK5lAJzJSrUWgpUnmp7W9t+gGlUBpTVggk=
  template:
    metadata:
      name: docker-config
      namespace: index-api-prod
    type: kubernetes.io/dockerconfigjson
