---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-config
  namespace: index-api-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCHrUGzEsp99mV7J1SjHk800aurMAYSQwz24fHUl7jMtY7t7w8KPXuqCKgFpw97h2MLGO7X8J6ufmt0ATL+UK+jMxLC6fm4/buv6A/zMR/Hbel4lKOekswds/AeMJn/bufatFFlp1iv1wwdkn7qy/orZEdIaGfGkOPXy7XqcN81pwYwHa2WbYomvZ4u8c0YgMA6TGOc5W09aiQpUpttUgLtefCrJz1Q/a0FVjIO/6YvMlhuHpf5Hg4+KS4wcDcDZVvqpfSkzVldePtn5JSvynL6XpVgYT6T+ELaWiWfAGtQWcJZ9lBMi8rHABYYi/opEqX4nh5NYztN4WVLAXzpvsBDv2GKTnRLFcVTw8phd7h6HsUDVw2hdq8PgG+H3sewoF3ObO8zggu+f/2FwYNdfmu24+fCJqj/28KqouRu1LM2p0D8hQYPuk+v9D3nmIdquQo7tp+hh0kbVKjT6n8HVlTgBikwoGKXSIB/NkiiS5jmT/haco13RuShpJnTcwXDN+bxws0bOOqT3PWBMWJv41VqLHOT2jcCvMie5PXWkYK1pAw+6kWFVNvoGX4KJA5KPJV5DPdzgeS63/L6B+GIAVBSWgD7DKEISTtcfCj8LJ5tcVVl16hLNUppLCCri9eygxCKDjRalXVeEs5Hh8tSEzlLOwInJbJ0Ut5fwIm1AupZthhi4/RQllKmt0i3ILNarjXGKMU6kk9tNyuMMH4Dn9Tt+kvdBx8kDrcrCTEexDpN5p1B4lsqilydTPzaO+/T7dzixNbVrYF7sW+HLj59G0ThuMiPJDGXy0epIaSupYSbBQEatMBPcIb1bOL2SrL45Tv0b47TNGUJJmc4wD8zja4XT5du6HmlYXUnDH9lThHnemH47M+D65rt/OHqn/IaHlQhkPM7JNTma3u9t9haRoTZkF/aMcWRaubdxq26Y2U=
  template:
    metadata:
      name: docker-config
      namespace: index-api-prod
    type: kubernetes.io/dockerconfigjson
