apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: index
namePrefix: prod-

resources:
  - ../../base

patches:
  - path: replicas.yml
  - path: version.yml
  - path: docker-registry-secret-sealed.yml
