---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: eu.gcr.io/index-352608/index-api-main@sha256:6b224918a4324d646e50e21096d47192083bd17da1098c0cb48b4c90bb195689
