apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: index-api-prod # {app-name}-{env-name}
data:
  .dockerconfigjson: # instructions in apps/index-api/README.md
type: kubernetes.io/dockerconfigjson
