apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account
  namespace: index-api-prod
type: Opaque
data:
  # Base64-encode the contents of your JSON file
  key.json: # see /apps/index-api/README.md for instructions