---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgBo0lawyiHoZMFfmFLnbdzoMNmFG1wQ6sjVqkkfDeuXl4eknRjuYplyFlBz8oy3UGhFDdhD7WYQtvBdhJqOk1AZDn1d9MIovQlsaqfvgqvfBrYsz3O70HLkUmiY03EnFX7b+x4VdJtKPqkMWj6FWG0KHyP4nNU6+/e9Q1KnCHl8GWMcGcoGq7YDtAAQkD+Qee7Wb/KonULePySD4jYeudQCKbPIS5Hi9598N5k8/jqqsparaX4/I/KnuMIlmN0lHDRZ7JjYL+vMDZCnUh2WAYm5fesvStQu+OHaB5TJ2sXG6nulooYYp4j7Pge1XBWG9BSO3Mljm8sXskO+0g6fmPMDlxtVFUWwL58AuyPqqqM4h2chknTbfeuHkiMt+jC/y3tlX1tNX9ZHOuyOqx0LemtNlyjxI19fen+ml0xCBUCAL7ncgtpzw3n4LEaS5iinlzwH12OSYo/KNA6heBkh/Q2O7GN2vE3yOb52uJzKuwmqFl3xhK/sKj66kJks5wuSI0X0yB4yPWpV7irosdZQvwpnNRwmzeME+ovZqPWlzJPwgbQl/08yv+j/i5OX8XPLl8qGuugB7VJEdUq3NhZV4ifjDDreJKzoHpkI5Y0rAc+vEPxObkxF2CqK96iDyGrxPZnK/T9CACKmjo1rJ/M7Qttr2aS7KFolp9DGolasiHa4EfuSOODqWN9RnuVF35HMS6p9sOqLieeoYDF9Gb+a30nytQ4rW8BJAn+ENCKwXDePjOhooa5Aso5zrTON4fAuYrk6pZjAtvJgEqp9exJkMJyr
  template:
    metadata:
      name: postgresql-auth
      namespace: postgresql-prod
    type: Opaque
