apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-auth-secret-sealed.yml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18
    releaseName: postgresql
    namespace: index-postgresql-prod
    valuesFile: pg-values.yml
