apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-auth
  namespace: index-postgresql-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgBo7wQUJ+ip110a40ePTdwh3Qs+BmnZdD5Ad24+2bN0MbtA3XsG+1uydzCcNqVAtoTCAbBssHFD2lFbs03KRc5bM2g2q3hKurgCXzo3FLYDGxXxfPTImmAUoMuUDWcLtEtyH6A6QA3RkEwIAn0MvtdvaTqyKcsP6irn67v5Lj6xGBY0IuKqUMhRbqmELNRzjn2eNlbxWJXTFWBtRtFEindiRIjOccuIx4yw8deY5+M+d9j6/3C4gNZFVJpdxoZDvnhRKs7I8RbQDLShBfg7jsa3p6hTB2gx64TgPnGUdigdMCPReucP7joxmEotZ78pUnEYnTbo1k+2YWdK7pxOsVmw7cNrYt0Qbh94DQWMAUBs17T3x3UxSXKbT5oCs3GmUucjmljs/OR1+h4cjlyuts/MS0GEgs/Emi7mHMFShlxENEohBayVL6hZzmrypnqjQmXRNwsuNg3yhnjkNxVSXvgfWNFKB1UCUKgaRSziGBcSLkXnAm5cUAiCGag2b0IbW7No8jC5ZWiQAGKPfzz+i/Z4rf0MB6HdR+ic84bPDAQZcXTQ9oZ+vW8YguvlHbHVGBqwLLkDMK/QKCZjeEQb4B0E2X54yVAP/PksMOmj95EfLmLBaBHiguQ3ETX59VGcpI2v2rCB4LOJWAV8f1X3jBD+9qiiRz9loTznrxDq8MMKydW1skYqJeuY3plEiGOrVM7SYMMGdEuROhOigqjBfmWarfgHeL/BAnbli32xoNMRAbf+lJYx5WlB2acKdgIkUinUZ6J0zq1jso9SmLf///9F
  template:
    metadata:
      name: postgresql-auth
      namespace: index-postgresql-prod
    type: Opaque
