---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    metadata:
      name: docker-config
      namespace: index-api-prod
    type: kubernetes.io/dockerconfigjson
