---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gcp-service-account
  namespace: index-postgresql-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    metadata:
      name: gcp-service-account
    type: Opaque
