apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yml
  - service.yml
  - deployment.yml
  - docker-config-secret-sealed.yml
  - gcp-service-account-secret-sealed.yml
